In [100]:
import xml.etree.ElementTree as ET
import matplotlib.pyplot as plt
from operator import itemgetter
from matplotlib.patches import Arc

import os
import pandas as pd
import numpy as np
import statistics

In [75]:
os.getcwd()

'/Users/alejandrocasares/Desktop/02_Master/M12_PFM/PFM2'

In [76]:
datos = pd.DataFrame([],[])
for i in np.arange(1,39):    
    temporal = pd.read_csv(('Data/J'+str(i)+'.csv'),sep=';')
    temporal['Jornada'] = 'J'+str(i)
    datos = pd.concat([datos,temporal])

In [77]:
datos

,player_id,id,event_id,type_id,period_id,min,sec,team_id,outcome,x,...,289,67,381,436,187,313,300,330,329,245
0,100868.0,2210429275,593,1,2,66,8,176,0,25.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100868.0,2210344463,234,12,1,26,31,176,1,23.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100868.0,2210469203,792,1,2,91,46,176,1,12.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100868.0,2210399159,461,49,2,50,25,176,1,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100868.0,2210336175,179,1,1,21,18,176,1,24.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1552,NaN,2301816273,339,30,1,47,0,185,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1553,NaN,2301839281,586,43,2,86,39,185,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1554,NaN,2301838143,577,40,2,81,22,185,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1555,NaN,2301802421,254,27,1,25,49,176,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1556,NaN,2301816275,409,30,1,47,0,176,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
datos['Jornada']

0        J1
1        J1
2        J1
3        J1
4        J1
       ...
1552    J38
1553    J38
1554    J38
1555    J38
1556    J38
Name: Jornada, Length: 71344, dtype: object

In [79]:
datos.shape

(71344, 269)

In [80]:
descriptivos_f24 = pd.read_excel('Data/f24_type_id.xlsx',sheet_name="Hoja1")

In [81]:
descriptivos_f24

    type_id            Description                    Descripción
0         1                  Pass                           Pase
1         2          Offside Pass         Pase en fuera de juego
2         3               Take On                          Regate
3         4                  Foul                          Falta
4         5                   Out                          Fuera
..      ...                    ...                            ...
65       74          Blocked Pass                 Pase bloqueado
66       75         Delayed Start           Retraso en la salida
67       76             Early end                 Fin anticipado
68       77      Player Off Pitch        Jugador fuera del campo
69       79  Coverage interuption   Interrupción de la cobertura

[70 rows x 3 columns]

In [82]:
datos = pd.merge(datos, descriptivos_f24, how='left', on='type_id')

In [ ]:
datos.shape()

In [83]:
datos[['type_id','Descripción','Jornada','player_id']]

       type_id              Descripción Jornada  player_id
0            1                    Pase       J1   100868.0
1           12                 Despeje       J1   100868.0
2            1                    Pase       J1   100868.0
3           49  Recuperación del balón       J1   100868.0
4            1                    Pase       J1   100868.0
...        ...                      ...     ...        ...
71339       30           Retraso final      J38        NaN
71340       43        Evento eliminado      J38        NaN
71341       40     Cambio de formación      J38        NaN
71342       27       Retraso de inicio      J38        NaN
71343       30           Retraso final      J38        NaN

[71344 rows x 4 columns]

In [84]:
jornadas = pd.read_excel('Data/Jornadas.xlsx',sheet_name="Sheet1")

In [85]:
jornadas

,Jornada,Hora,Día,Fecha,Rival,Resultado,Lugar,Marcador,Equipo,Nombre Completo,Abrebiatura,Estadio,Latitud,Longitud,Altitud,Distancia,Tiempo_Viaje,Altitud_std,Distancia_std,Cluster
0,J1,16:00:00,S,2020-09-12,Eibar,Empate,Fuera,0:0,Eibar,Sociedad Deportiva Eibar S.A.D.,EIB,Ipurúa,43°10′54″N,2°28′33″O,339,713,1h 10min,0.225105,-0.200495,2
1,J2,18:30:00,D,2021-01-24,Eibar,Empate,Casa,1:1,Eibar,Sociedad Deportiva Eibar S.A.D.,EIB,Ipurúa,43°10′54″N,2°28′33″O,339,713,1h 10min,0.225105,-0.200495,2
2,J3,18:30:00,S,2020-09-19,Valencia,Ganado,Casa,2:1,Valencia,Valencia Club de Futbol S.A.D.,VAL,Mestalla,39°28′29″N,0°21′30″O,11,1000,1h 20min,-1.013727,0.956127,1
3,J4,18:30:00,S,2021-02-20,Valencia,Derrota,Fuera,2:0,Valencia,Valencia Club de Futbol S.A.D.,VAL,Mestalla,39°28′29″N,0°21′30″O,11,1000,1h 20min,-1.013727,0.956127,1
4,J5,18:30:00,D,2020-09-27,Real Valladolid,Empate,Fuera,1:1,Real Valladolid,Real Valladolid Club de Futbol S.A.D.,VLL,José Zorrilla,41°38′40″N,4°45′40″O﻿,725,435,NaN,1.682999,-1.320846,0
5,J6,14:00:00,D,2021-02-28,Real Valladolid,Empate,Casa,1:1,Real Valladolid,Real Valladolid Club de Futbol S.A.D.,VLL,José Zorrilla,41°38′40″N,4°45′40″O﻿,725,435,NaN,1.682999,-1.320846,0
6,J7,19:00:00,J,2020-10-01,Barcelona,Derrota,Casa,0:3,Barcelona,Fútbol Club Barcelona,FCB,Camp Nou,41°22′51″N,2°07′21″E,190,1141,1h 40min,-0.337657,1.524363,1
7,J8,18:30:00,D,2021-05-16,Barcelona,Ganado,Fuera,2:1,Barcelona,Fútbol Club Barcelona,FCB,Camp Nou,41°22′51″N,2°07′21″E,190,1141,1h 40min,-0.337657,1.524363,1
8,J9,21:00:00,D,2020-10-04,Osasuna,Derrota,Fuera,2:0,Osasuna,Club Atlético Osasuna,OSA,El Sadar,42°47′48″N,1°38′13″O,432,762,NaN,0.576359,-0.003023,2
9,J10,18:30:00,D,2021-04-25,Osasuna,Ganado,Casa,2:1,Osasuna,Club Atlético Osasuna,OSA,El Sadar,42°47′48″N,1°38′13″O,432,762,NaN,0.576359,-0.003023,2
10,J11,16:00:00,S,2020-10-17,Atlético,Derrota,Casa,2:0,Atlético,Club Atlético de Madrid,ATM,Wanda Metropolitano,40°26′10″N,3°35′58″O,664,677,1h 10min,1.452606,-0.345576,0
11,J12,21:00:00,L,2021-02-08,Atlético,Empate,Fuera,2:2,Atlético,Club Atlético de Madrid,ATM,Wanda Metropolitano,40°26′10″N,3°35′58″O,664,677,1h 10min,1.452606,-0.345576,0
12,J13,21:00:00,L,2020-10-26,Levante,Empate,Fuera,1:1,Levante,Levante Unión Deportiva S.A.D.,LEV,Ciutat de Valencia,39°29′41″N,0°21′51″O,11,992,1h 20min,-1.013727,0.923887,1
13,J14,21:00:00,V,2021-04-30,Levante,Ganado,Casa,2:0,Levante,Levante Unión Deportiva S.A.D.,LEV,Ciutat de Valencia,39°29′41″N,0°21′51″O,11,992,1h 20min,-1.013727,0.923887,1
14,J15,16:00:00,D,2020-11-01,Real Sociedad,Derrota,Casa,4:1,Real Sociedad,Real Sociedad S.A.D.,RSO,Anoeta,43°18′05″N,1°58′25″O,191,757,NaN,-0.333880,-0.023173,1
15,J16,21:00:00,J,2021-04-22,Real Sociedad,Derrota,Fuera,2:1,Real Sociedad,Real Sociedad S.A.D.,RSO,Anoeta,43°18′05″N,1°58′25″O,191,757,NaN,-0.333880,-0.023173,1
16,J17,21:00:00,V,2020-11-06,Elche,Empate,Fuera,1:1,Elche,Elche Club de Futbol S.A.D.,ELC,Martínez Valero,38°16′01″N,0°39′48″O,76,1009,1h 30min,-0.768227,0.992398,1
17,J18,21:00:00,V,2021-02-12,Elche,Ganado,Casa,3:1,Elche,Elche Club de Futbol S.A.D.,ELC,Martínez Valero,38°16′01″N,0°39′48″O,76,1009,1h 30min,-0.768227,0.992398,1
18,J19,18:30:00,S,2020-11-21,Sevilla,Derrota,Fuera,2:4,Sevilla,Sevilla Fútbol Club,SEV,Ramón Sánchez-Pizjuán,37°23′02″N,5°58′14″O,14,727,1h 25min,-1.002397,-0.144074,1
19,J20,21:00:00,L,2021-04-12,Sevilla,Derrota,Casa,4:3,Sevilla,Sevilla Fútbol Club,SEV,Ramón Sánchez-Pizjuán,37°23′02″N,5°58′14″O,14,727,1h 25min,-1.002397,-0.144074,1
20,J21,18:30:00,D,2020-11-29,Granada,Ganado,Casa,3:1,Granada,Granada Clubde Fútbil,GRA,Los Carmenes,37°09′11″N,3°35′45″O,475,1014,NaN,0.738767,1.012548,2
21,J22,18:30:00,D,2021-01-31,Granada,Empate,Fuera,0:0,Granada,Granada Clubde Fútbil,GRA,Los Carmenes,37°09′11″N,3°35′45″O,475,1014,NaN,0.738767,1.012548,2
22,J23,21:00:00,V,2020-12-04,Athletic,Ganado,Fuera,2:0,Athletic,Athletic Club,ATH,San Mamés,43°15′51″N,2°56′58″O,54,610,1h 10min,-0.851320,-0.615589,1
23,J24,14:00:00,D,2021-03-14,Athletic,Empate,Casa,0:0,Athletic,Athletic Club,ATH,San Mamés,43°15′51″N,2°56′58″O,54,610,1h 10min,-0.851320,-0.615589,1
24,J25,21:00:00,L,2020-12-14,Cádiz,Ganado,Casa,4:0,Cádiz,Cádiz Club de Fútbol S.A.D.,CDZ,Nuevo Mirandilla,36°30′10″N,6°16′23″O,0,841,NaN,-1.055274,0.315351,1
25,J26,18:30:00,D,2021-04-18,Cádiz,Empate,Fuera,0:0,Cádiz,Cádiz Club de Fútbol S.A.D.,CDZ,Nuevo Mirandilla,36°30′10″N,6°16′23″O,0,841,NaN,-1.055274,0.315351,1
26,J27,14:00:00,D,2020-12-20,Alavés,Ganado,Casa,2:0,Alavés,Deportivo Alavés S.A.D.,ALV,Mendizorroza,42°50′14″N,2°41′17″O,517,656,NaN,0.897398,-0.430207,0
27,J28,14:00:00,D,2021-04-04,Alavés,Ganado,Fuera,3:1,Alavés,Deportivo Alavés S.A.D.,ALV,Mendizorroza,42°50′14″N,2°41′17″O,517,656,NaN,0.897398,-0.430207,0
28,J29,16:30:00,X,2020-12-23,Getafe,Empate,Fuera,1:1,Getafe,Getafe Club de Futbol S.A.D.,GET,Coliseum Alfonso Pérez,40°19′32″N,3°42′53″O,629,602,1h 10min,1.320414,-0.647829,0
29,J30,20:00:00,X,2021-05-12,Getafe,Ganado,Casa,1:0,Getafe,Getafe Club de Futbol S.A.D.,GET,Coliseum Alfonso Pérez,40°19′32″N,3°42′53″O,629,602,1h 10min,1.320414,-0.647829,0
30,J31,19:15:00,X,2020-12-30,Huesca,Ganado,Casa,2:1,Huesca,Sociedad Deportiva Huesca S.A.D.,HUE,El Alcoraz,42°07′55″N,0°25′28″O,485,911,NaN,0.776536,0.597454,2
31,J32,14:00:00,D,2021-03-07,Huesca,Ganado,Fuera,4:3,Huesca,Sociedad Deportiva Huesca S.A.D.,HUE,El Alcoraz,42°07′55″N,0°25′28″O,485,911,NaN,0.776536,0.597454,2
32,J33,21:00:00,S,2021-01-02,Real Madrid,Derrota,Fuera,2:0,Real Madrid,Real Madrid Club de Fútbol,RMA,Santigo Bernabeu,40°27′11″N,3°41′18″O,698,678,1h 10min,1.581022,-0.341546,0
33,J34,16:15:00,S,2021-03-20,Real Madrid,Derrota,Casa,3:1,Real Madrid,Real Madrid Club de Fútbol,RMA,Santigo Bernabeu,40°27′11″N,3°41′18″O,698,678,1h 10min,1.581022,-0.341546,0
34,J35,21:00:00,V,2021-01-08,Villarreal,Derrota,Casa,4:0,Villarreal,Villareal Club de Futbol S.A.D.,VIL,La Cerámica,39°56′39″N,0°06′13″O,44,1004,1h 20min,-0.889089,0.972247,1
35,J36,18:30:00,D,2021-05-09,Villarreal,Ganado,Fuera,4:2,Villarreal,Villareal Club de Futbol S.A.D.,VIL,La Cerámica,39°56′39″N,0°06′13″O,44,1004,1h 20min,-0.889089,0.972247,1
36,J37,21:00:00,X,2021-01-20,Betis,Derrota,Fuera,1:2,Betis,Real Betis Balompié,BET,Benito Villamarín,37°21′23″N,5°58′54″O,11,726,1h 25min,-1.013727,-0.148104,1
37,J38,18:00:00,S,2021-05-22,Betis,Derrota,Casa,3:2,Betis,Real Betis Balompié,BET,Benito Villamarín,37°21′23″N,5°58′54″O,11,726,1h 25min,-1.013727,-0.148104,1

In [86]:
datos = pd.merge(datos, jornadas, how='left', on='Jornada')

In [87]:
datos.shape

(71344, 290)

In [104]:
datos[(datos['Lugar']== 'Casa') & (datos['type_id']==16) & (datos['team_id'] == 176)].count

<bound method DataFrame.count of        player_id          id  event_id  type_id  period_id  min  sec  team_id  \
3055     40270.0  2213083337       478       16          2   56    9      176
3086     40270.0  2213056975       116       16          1   12   41      176
4841     40270.0  2216563325       377       16          1   43   59      176
12409   439871.0  2226398651       441       16          2   51   59      176
18539    40270.0  2235197653        97       16          1    9   49      176
18941    86173.0  2235215823       310       16          1   35    9      176
20278   234511.0  2238802911       920       16          2   84    3      176
20412   437803.0  2238801225       901       16          2   80   20      176
20640    86173.0  2238763241       304       16          1   26   25      176
25575   178880.0  2247287521       235       16          1   18   23      176
25614   178880.0  2247350407       811       16          2   78   46      176
28030    40270.0  2248441711       150       16          1   16   21      176
37383   178880.0  2257592379       100       16          1    8   30      176
46172   107117.0  2270180339       938       16          2   93   32      176
55585   178880.0  2285871217       329       16          1   42   25      176
56149    40270.0  2285863373       200       16          1   22   47      176
56166    40270.0  2285861671       196       16          1   19   47      176
58223    76508.0  2289901291       184       16          1   21   25      176
62674   143710.0  2293134595       691       16          2   73   30      176
62857   178880.0  2293125615       507       16          2   50   16      176
64417   143710.0  2297052353       465       16          2   56   46      176
64483   150360.0  2297013037       176       16          1   18   46      176
64503   150360.0  2297022281       260       16          1   33   47      176
64560   178880.0  2297031413       337       16          1   47   35      176
70163   178880.0  2301822509       463       16          2   48   48      176
70747    40270.0  2301805311       286       16          1   31   25      176

       outcome     x  ...  Abrebiatura                 Estadio     Latitud  \
3055         1  81.1  ...          EIB                  Ipurúa  43°10′54″N
3086         1  92.5  ...          EIB                  Ipurúa  43°10′54″N
4841         1  98.9  ...          VAL                Mestalla  39°28′29″N
12409        1  96.8  ...          FCB                Camp Nou  41°22′51″N
18539        1  98.3  ...          OSA                El Sadar  42°47′48″N
18941        1  90.9  ...          OSA                El Sadar  42°47′48″N
20278        1  97.3  ...          ATM     Wanda Metropolitano  40°26′10″N
20412        1  97.0  ...          ATM     Wanda Metropolitano  40°26′10″N
20640        1  93.2  ...          ATM     Wanda Metropolitano  40°26′10″N
25575        1  93.5  ...          LEV      Ciutat de Valencia  39°29′41″N
25614        1  93.9  ...          LEV      Ciutat de Valencia  39°29′41″N
28030        1  88.5  ...          RSO                  Anoeta  43°18′05″N
37383        1  92.0  ...          SEV  Ramón Sánchez-Pizjuán   37°23′02″N
46172        1  93.9  ...          CDZ        Nuevo Mirandilla  36°30′10″N
55585        1  90.7  ...          GET  Coliseum Alfonso Pérez  40°19′32″N
56149        1  81.8  ...          GET  Coliseum Alfonso Pérez  40°19′32″N
56166        1  88.5  ...          GET  Coliseum Alfonso Pérez  40°19′32″N
58223        1  92.7  ...          HUE              El Alcoraz  42°07′55″N
62674        1  94.0  ...          RMA        Santigo Bernabeu  40°27′11″N
62857        1  96.0  ...          RMA        Santigo Bernabeu  40°27′11″N
64417        1  86.5  ...          VIL             La Cerámica  39°56′39″N
64483        1  91.2  ...          VIL             La Cerámica  39°56′39″N
64503        1  88.5  ...          VIL             La Cerámica  39°56′39″N
64560        1  88.5  ...          VIL             La Cerámica  39°56′39″N
70163        1  85.4  ...          BET       Benito Villamarín  37°21′23″N
70747        1  88.5  ...          BET       Benito Villamarín  37°21′23″N

        Longitud  Altitud Distancia  Tiempo_Viaje Altitud_std Distancia_std  \
3055   2°28′33″O      339       713      1h 10min    0.225105     -0.200495
3086   2°28′33″O      339       713      1h 10min    0.225105     -0.200495
4841   0°21′30″O       11      1000      1h 20min   -1.013727      0.956127
12409  2°07′21″E      190      1141      1h 40min   -0.337657      1.524363
18539  1°38′13″O      432       762           NaN    0.576359     -0.003023
18941  1°38′13″O      432       762           NaN    0.576359     -0.003023
20278  3°35′58″O      664       677      1h 10min    1.452606     -0.345576
20412  3°35′58″O      664       677      1h 10min    1.452606     -0.345576
20640  3°35′58″O      664       677      1h 10min    1.452606     -0.345576
25575  0°21′51″O       11       992      1h 20min   -1.013727      0.923887
25614  0°21′51″O       11       992      1h 20min   -1.013727      0.923887
28030  1°58′25″O      191       757           NaN   -0.333880     -0.023173
37383  5°58′14″O       14       727      1h 25min   -1.002397     -0.144074
46172  6°16′23″O        0       841           NaN   -1.055274      0.315351
55585  3°42′53″O      629       602      1h 10min    1.320414     -0.647829
56149  3°42′53″O      629       602      1h 10min    1.320414     -0.647829
56166  3°42′53″O      629       602      1h 10min    1.320414     -0.647829
58223  0°25′28″O      485       911           NaN    0.776536      0.597454
62674  3°41′18″O      698       678      1h 10min    1.581022     -0.341546
62857  3°41′18″O      698       678      1h 10min    1.581022     -0.341546
64417  0°06′13″O       44      1004      1h 20min   -0.889089      0.972247
64483  0°06′13″O       44      1004      1h 20min   -0.889089      0.972247
64503  0°06′13″O       44      1004      1h 20min   -0.889089      0.972247
64560  0°06′13″O       44      1004      1h 20min   -0.889089      0.972247
70163  5°58′54″O       11       726      1h 25min   -1.013727     -0.148104
70747  5°58′54″O       11       726      1h 25min   -1.013727     -0.148104

      Cluster
3055        2
3086        2
4841        1
12409       1
18539       2
18941       2
20278       0
20412       0
20640       0
25575       1
25614       1
28030       1
37383       1
46172       1
55585       0
56149       0
56166       0
58223       2
62674       0
62857       0
64417       1
64483       1
64503       1
64560       1
70163       1
70747       1

[26 rows x 290 columns]>